version: "2.3" #Use this version strictly
services:
  rabbitmq:
    image: "rabbitmq:3.10"
    restart: always
  redis-server:
    image: "redis"
    restart: always
  server:
    build: ./server
    restart: always
    ports:
      - "9000:7000"
  worker:
    build: ./workers
    restart: always
    pids_limit: 60 # Max number of processes running in thw container.
    cpus: 1 # No of CPUs allocated
    mem_limit: 150M # Hard limit
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

